name: site generator checks

on:
  pull_request:
    branches:
      - main
    paths:
      - '!packages/**'

jobs:
  site-lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: python3 -m pip install -r ./requirements.txt

      - name: '[Dry run] Generate repository data'
        run: python3 -m repogen -i ./packages -o ./content -D -L

      - name: '[Dry run] Generate site content'
        run: invoke build